// Project-wide TypeScript type definitions

// Visual style options
export type VisualStyle = 'default' | 'cinematic' | 'anime';

// Segment representing a script slice
export interface Segment {
  id: string;
  text: string;
  estimatedDuration?: number; // in seconds
}

// Pronunciation Dictionary Item
export interface PronunciationDictItem {
  text: string;
  pronunciation: string;
}

// Asset generation status
export type GenerationStatus = 'idle' | 'pending' | 'loading' | 'success' | 'error';

// Assets for each segment
export interface SegmentAssets {
  // Image prompt (generated by OpenAI)
  imagePrompt: string | null;
  promptStatus: GenerationStatus;
  promptError?: string;

  // Image (generated by Gemini)
  imageUrl: string | null;
  imageStatus: GenerationStatus;
  imageError?: string;

  // Audio (generated by Minimax TTS)
  audioUrl: string | null;
  audioStatus: GenerationStatus;
  audioError?: string;
  audioDuration?: number; // in seconds
  customPronunciations?: PronunciationDictItem[];

  // Voice settings (per-segment, with defaults)
  voiceSpeed?: number;    // default 1.2, range 0.5-2.0
  voiceEmotion?: string;  // default 'neutral'
}

// HeyGen integration state (Step 4)
export interface HeyGenState {
  mergedAudioUrl: string | null;      // Merged MP3 blob URL
  mergedAudioDuration: number | null; // Total duration in seconds
  heygenVideoFile: File | null;       // Uploaded HeyGen video
  heygenVideoUrl: string | null;      // Preview URL for the video
}

// Project state for the entire workflow
export interface ProjectState {
  // Step 1: Setup data
  avatar: File | null;
  avatarPreviewUrl: string | null;
  voiceId: string;
  visualStyle: VisualStyle;
  script: string;

  // Step 2: Sliced segments
  segments: Segment[];

  // Step 3: Generated assets (keyed by segment ID)
  generatedAssets: Map<string, SegmentAssets>;

  // Step 4: HeyGen integration
  heygen: HeyGenState;

  // Navigation state
  currentStep: 1 | 2 | 3 | 4 | 5;
}

// API Request/Response types
export interface SliceRequest {
  script: string;
}

export interface SliceResponse {
  segments: Segment[];
}

export interface GeneratePromptRequest {
  segmentId: string;
  text: string;
  style: VisualStyle;
}

export interface GeneratePromptResponse {
  segmentId: string;
  prompt: string;
}

export interface GenerateImageRequest {
  segmentId: string;
  prompt: string;
}

export interface GenerateImageResponse {
  segmentId: string;
  imageUrl: string;
}

export interface GenerateAudioRequest {
  segmentId: string;
  text: string;
  voiceId: string;
  pronunciationDict?: PronunciationDictItem[];
}

export interface GenerateAudioResponse {
  segmentId: string;
  audioUrl: string;
  duration: number;
}

export interface ExportRequest {
  avatarUrl: string;
  segments: Array<{
    id: string;
    text: string;
    imageUrl: string;
    audioUrl: string;
  }>;
}

export interface ExportResponse {
  videoUrl: string;
}

// Error response type
export interface ApiError {
  error: string;
  details?: string;
}
